//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aEntities : DbContext
    {
        public aEntities()
            : base("name=aEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<grup> grup { get; set; }
        public virtual DbSet<postupaushii> postupaushii { get; set; }
        public virtual DbSet<stipendiya> stipendiya { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<univer> univer { get; set; }
        public virtual DbSet<vipusk> vipusk { get; set; }
    }
}
