//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class postupaushii
    {
        public string Facultet { get; set; }
        public string familiya_postup { get; set; }
        public string imya_postup { get; set; }
        public int ball { get; set; }
        public int id { get; set; }
    
        public virtual univer univer { get; set; }
    }
}
