//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class stipendiya
    {
        public Nullable<int> Num_gr { get; set; }
        public string familiya { get; set; }
        public string imya { get; set; }
        public Nullable<int> viplata { get; set; }
        public int id { get; set; }
    
        public virtual grup grup { get; set; }
    }
}
